apiVersion: v1
kind: Secret
metadata:
  name: account-service-db-secret
  namespace: account-service
  labels:
    app.kubernetes.io/name: ms-account-service
    app.kubernetes.io/component: database
type: Opaque
stringData:
  # Replace with actual values or manage via External Secrets / Sealed Secrets
  SPRING_DATASOURCE_URL: "jdbc:postgresql://<POSTGRES_FQDN>:5432/fintech_accounts?sslmode=require"
  SPRING_DATASOURCE_USERNAME: "<POSTGRES_USERNAME>"
  SPRING_DATASOURCE_PASSWORD: "<POSTGRES_PASSWORD>"
